services:
  postgres:
    container_name: test_db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
